version: '2'

services:
  postgresql:
    image: postgres:11.8-alpine
    environment:
      POSTGRES_PASSWORD: it_dev
      POSTGRES_USER: it_dev
      POSTGRES_DB: it_dev
    ports:
      - '5432:5432'
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
      - '85:80'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: fiorenzino@gmail.com
      PGADMIN_DEFAULT_PASSWORD: flower
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
  it-dev-services:
    image: it-dev/it-dev-services:latest
    depends_on:
      - postgresql
      - minio
    ports:
      - 8080:8080
    environment:
      QUARKUS_OIDC_CLIENT_ID: it_dev_services
      QUARKUS_OIDC_AUTH_SERVER_URL: https://sso.e-g.gs/auth/realms/it_dev
      QUARKUS_DATASOURCE_USERNAME: it_dev
      QUARKUS_DATASOURCE_PASSWORD: it_dev
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql:5432/it_dev
      QUARKUS_S3_ENDPOINT_OVERRIDE: http://minio:9001
      QUARKUS_S3_AWS_REGION: us-east-1
      QUARKUS_S3_AWS_CREDENTIALS_TYPE: static
      QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_ACCESS_KEY_ID: minio
      QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_SECRET_ACCESS_KEY_ID : minio123
      BUCKET_NAME: it-dev
